apiVersion: v1      # Vericar versao da api referente ao manifesto de pod atraves do comando (kubectl api-resources)
kind: Pod
metadata:
  name: meupod
spec:
  containers:
    - name: web
      image: kubedevio/web-color:blue
      ports:
        - name: http
          containerPort: 80
          protocol: TCP