apiVersion: apps/v1      # Vericar versao da api referente ao manifesto de deployment atraves do comando (kubectl api-resources)
kind: Deployment         # Embora a estrutura seja semelhante à de um ReplicaSet, o Deployment oferece funcionalidades adicionais, como a capacidade de fazer atualizações de maneira declarativa e rollback automático.
metadata: 
  name: meudeployment
spec:
  replicas: 1
  selector:
    matchLabels:           
      app: web             # O rótulo 'app: web' no selector deve coincidir com o rótulo especificado no template para que o Deployment gerencie esses pods.
  template:
    metadata:
      labels:              
        app: web           # Este rótulo 'app: web' no template deve coincidir com o rótulo no selector acima para garantir que os pods sejam gerenciados por este Deployment.
    spec:
      containers:
      - name: web
        image: kubedevio/web-color:blue
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
