apiVersion: apps/v1       # Vericar versao da api referente ao manifesto de replicaset atraves do comando (kubectl api-resources)
kind: ReplicaSet
metadata: 
  name: meureplicaset
spec:
  replicas: 1
  selector:
    matchLabels:           
      app: web             # O r贸tulo 'app: web' no selector deve coincidir com o r贸tulo especificado no template para que o ReplicaSet gerencie esses pods.
  template:
    metadata:
      labels:              
        app: web           # Este r贸tulo 'app: web' no template deve coincidir com o r贸tulo no selector acima para garantir que os pods sejam gerenciados por este ReplicaSet.
    spec:
      containers:
      - name: web
        image: kubedevio/web-color:blue
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
